services:
  web:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env.local
    environment:
      - REMOTE_CHROME=ws://chrome:3000
    volumes:
      - ./data:/app/data
    restart: unless-stopped

  daemon:
    build: .
    command: npm run start-daemon
    env_file:
      - .env.local
    environment:
      - REMOTE_CHROME=ws://chrome:3000
    volumes:
      - ./data:/app/data
    restart: unless-stopped

  chrome:
    image: browserless/chrome:latest
    ports:
      - "9222:3000"
    restart: unless-stopped
